source "https://rubygems.org"

git_source(:github) {|just-the-docs| "https://github.com/#just-the-docs" }

group :jekyll_plugins do
  gem 'jekyll-feed', '~> 0.12'
  gem 'jekyll-remote-theme'
  gem 'jekyll-sitemap'
  gem 'jekyll-seo-tag'
end
