source "https://rubygems.org"

# git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

group :jekyll_plugins do
  gem 'jekyll-feed', '~> 0.12'
  gem 'jekyll-remote-theme'
  gem 'jekyll-sitemap'
  gem 'jekyll-seo-tag'
end
